{% set data= load_setup_py_data() %}
package:
  name: ts-standardscripts
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - astroquery
    - ts-atdome
    - ts-atdometrajectory
    - ts-atmcs-simulator
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-observatory-control
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test -vxs

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
    - ts-observatory-control
